"""empty message

Revision ID: 607922bdb751
Revises: e5cec5893e0d
Create Date: 2024-05-25 23:15:26.286287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607922bdb751'
down_revision: Union[str, None] = 'e5cec5893e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('IMOVEIS_ibfk_1', 'IMOVEIS', type_='foreignkey')
    op.add_column('VISTORIAS', sa.Column('data_criacao', sa.String(length=36), nullable=True))
    op.add_column('VISTORIAS', sa.Column('documento', sa.String(length=36), nullable=True))
    op.add_column('VISTORIAS', sa.Column('id_contrato', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'VISTORIAS', 'CONTRATOS', ['id_contrato'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VISTORIAS', type_='foreignkey')
    op.drop_column('VISTORIAS', 'id_contrato')
    op.drop_column('VISTORIAS', 'documento')
    op.drop_column('VISTORIAS', 'data_criacao')
    op.create_foreign_key('IMOVEIS_ibfk_1', 'IMOVEIS', 'IMAGENS', ['id'], ['id'])
    # ### end Alembic commands ###
