"""empty message

Revision ID: 762ebd48ea27
Revises: 9d73b3fee5da
Create Date: 2024-05-26 17:17:58.077606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762ebd48ea27'
down_revision: Union[str, None] = '9d73b3fee5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CONTRATOS_ibfk_5', 'CONTRATOS', type_='foreignkey')
    op.create_foreign_key(None, 'CONTRATOS', 'VISTORIAS', ['contestecao_vistoria_inicial_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CONTRATOS', type_='foreignkey')
    op.create_foreign_key('CONTRATOS_ibfk_5', 'CONTRATOS', 'VISTORIAS', ['contestecao_vistoria_inicial_id'], ['id'])
    # ### end Alembic commands ###
