"""empty message

Revision ID: 928df90c755b
Revises: f1d21d26a53e
Create Date: 2024-05-25 21:07:56.688015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '928df90c755b'
down_revision: Union[str, None] = 'f1d21d26a53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IMAGENS', sa.Column('id_entidade', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'IMAGENS', 'VISTORIAS', ['id_entidade'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'OCORRENCIAS', ['id_entidade'], ['id'])
    op.add_column('VISTORIAS', sa.Column('descricao', sa.String(length=500), nullable=True))
    op.add_column('VISTORIAS', sa.Column('vistoria_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'VISTORIAS', 'VISTORIAS', ['vistoria_id'], ['id'])
    op.drop_column('VISTORIAS', 'esta_fechada_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VISTORIAS', sa.Column('esta_fechada_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'VISTORIAS', type_='foreignkey')
    op.drop_column('VISTORIAS', 'vistoria_id')
    op.drop_column('VISTORIAS', 'descricao')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_column('IMAGENS', 'id_entidade')
    # ### end Alembic commands ###
