"""empty message

Revision ID: addcab310ac0
Revises: 
Create Date: 2024-05-26 20:31:17.623328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'addcab310ac0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SOLICITACOES', 'status',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Enum('ABERTO', 'FECHADO', name='status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SOLICITACOES', 'status',
               existing_type=sa.Enum('ABERTO', 'FECHADO', name='status'),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
