"""empty message

Revision ID: ba71461d2a09
Revises: e5cec5893e0d
Create Date: 2024-05-25 22:06:44.786507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba71461d2a09'
down_revision: Union[str, None] = 'e5cec5893e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ASSISTENTES', 'nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('CONTRATOS', sa.Column('contestecao_vistoria_inicial_id', sa.String(length=36), nullable=True))
    op.drop_index('fk_vistoria_final', table_name='CONTRATOS')
    op.drop_index('fk_vistoria_inicial', table_name='CONTRATOS')
    op.drop_constraint('fk_criador', 'CONTRATOS', type_='foreignkey')
    op.drop_constraint('fk_imoveis', 'CONTRATOS', type_='foreignkey')
    op.drop_constraint('fk_locatario', 'CONTRATOS', type_='foreignkey')
    op.create_foreign_key(None, 'CONTRATOS', 'VISTORIAS', ['vistoria_inicial_id'], ['id'])
    op.create_foreign_key(None, 'CONTRATOS', 'LOCATARIOS', ['locatario_id'], ['id'])
    op.create_foreign_key(None, 'CONTRATOS', 'IMOVEIS', ['imovel_id'], ['id'])
    op.create_foreign_key(None, 'CONTRATOS', 'VISTORIAS', ['contestecao_vistoria_inicial_id'], ['id'])
    op.drop_column('CONTRATOS', 'funcionario_criador_id')
    op.drop_column('CONTRATOS', 'vistoria_final_id')
    op.add_column('DOCUMENTOS', sa.Column('documento', sa.LargeBinary(), nullable=True))
    op.alter_column('DOCUMENTOS', 'vistoria_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'DOCUMENTOS', 'VISTORIAS', ['vistoria_id'], ['id'])
    op.drop_column('DOCUMENTOS', 'documentos')
    op.add_column('IMAGENS', sa.Column('id_imovel', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_ocorrencia', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_solicitacao', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_vistoria', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'IMAGENS', 'VISTORIAS', ['id_vistoria'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'OCORRENCIAS', ['id_ocorrencia'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'IMOVEIS', ['id_imovel'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'SOLICITACOES', ['id_solicitacao'], ['id'])
    op.alter_column('IMOVEIS', 'codigo',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('IMOVEIS', 'endereco',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('LOCATARIOS', 'nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('LOCATARIOS', 'data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('OCORRENCIAS', 'titulo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'descricao',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ABERTO', 'FECHADO', name='status'),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'data_criacao',
               existing_type=sa.DATE(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'id_contrato',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_column('OCORRENCIAS', 'prioridade')
    op.add_column('PRESTADORES_SERVICOS', sa.Column('experiencia', sa.Integer(), nullable=True))
    op.drop_column('PRESTADORES_SERVICOS', 'empresa')
    op.drop_column('PRESTADORES_SERVICOS', 'data_nascimento')
    op.alter_column('SOLICITACOES', 'titulo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('SOLICITACOES', 'descricao',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('SOLICITACOES', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ABERTO', 'FECHADO', name='status'),
               existing_nullable=True)
    op.alter_column('SOLICITACOES', 'data_criacao',
               existing_type=sa.DATE(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.create_foreign_key(None, 'SOLICITACOES', 'CONTRATOS', ['contrato_id'], ['id'])
    op.drop_column('SOLICITACOES', 'prioridade')
    op.create_foreign_key(None, 'USUARIOS_OCORRENCIAS', 'USUARIOS_IDENTITY_INFOS', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'USUARIOS_OCORRENCIAS', 'OCORRENCIAS', ['ocorrencia_id'], ['id'])
    op.add_column('VISTORIAS', sa.Column('descricao', sa.String(length=500), nullable=True))
    op.drop_column('VISTORIAS', 'e_contestacao')
    op.drop_column('VISTORIAS', 'contra_vistoria')
    op.drop_column('VISTORIAS', 'esta_fechada')
    op.drop_column('VISTORIAS', 'imovel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VISTORIAS', sa.Column('imovel_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('VISTORIAS', sa.Column('esta_fechada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('VISTORIAS', sa.Column('contra_vistoria', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('VISTORIAS', sa.Column('e_contestacao', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('VISTORIAS', 'descricao')
    op.drop_constraint(None, 'USUARIOS_OCORRENCIAS', type_='foreignkey')
    op.drop_constraint(None, 'USUARIOS_OCORRENCIAS', type_='foreignkey')
    op.add_column('SOLICITACOES', sa.Column('prioridade', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'SOLICITACOES', type_='foreignkey')
    op.alter_column('SOLICITACOES', 'data_criacao',
               existing_type=sa.String(length=36),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('SOLICITACOES', 'status',
               existing_type=sa.Enum('ABERTO', 'FECHADO', name='status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('SOLICITACOES', 'descricao',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('SOLICITACOES', 'titulo',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('PRESTADORES_SERVICOS', sa.Column('data_nascimento', sa.DATE(), nullable=True))
    op.add_column('PRESTADORES_SERVICOS', sa.Column('empresa', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('PRESTADORES_SERVICOS', 'experiencia')
    op.add_column('OCORRENCIAS', sa.Column('prioridade', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('OCORRENCIAS', 'id_contrato',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('OCORRENCIAS', 'data_criacao',
               existing_type=sa.String(length=36),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'status',
               existing_type=sa.Enum('ABERTO', 'FECHADO', name='status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'descricao',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('OCORRENCIAS', 'titulo',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('LOCATARIOS', 'data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('LOCATARIOS', 'nome',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('IMOVEIS', 'endereco',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('IMOVEIS', 'codigo',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_column('IMAGENS', 'id_vistoria')
    op.drop_column('IMAGENS', 'id_solicitacao')
    op.drop_column('IMAGENS', 'id_ocorrencia')
    op.drop_column('IMAGENS', 'id_imovel')
    op.add_column('DOCUMENTOS', sa.Column('documentos', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'DOCUMENTOS', type_='foreignkey')
    op.alter_column('DOCUMENTOS', 'vistoria_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_column('DOCUMENTOS', 'documento')
    op.add_column('CONTRATOS', sa.Column('vistoria_final_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('CONTRATOS', sa.Column('funcionario_criador_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'CONTRATOS', type_='foreignkey')
    op.drop_constraint(None, 'CONTRATOS', type_='foreignkey')
    op.drop_constraint(None, 'CONTRATOS', type_='foreignkey')
    op.drop_constraint(None, 'CONTRATOS', type_='foreignkey')
    op.create_foreign_key('fk_locatario', 'CONTRATOS', 'LOCATARIOS', ['locatario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_imoveis', 'CONTRATOS', 'IMOVEIS', ['imovel_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_criador', 'CONTRATOS', 'USUARIOS_IDENTITY_INFOS', ['funcionario_criador_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('fk_vistoria_inicial', 'CONTRATOS', ['vistoria_inicial_id'], unique=False)
    op.create_index('fk_vistoria_final', 'CONTRATOS', ['vistoria_final_id'], unique=False)
    op.drop_column('CONTRATOS', 'contestecao_vistoria_inicial_id')
    op.alter_column('ASSISTENTES', 'nome',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
