"""empty message

Revision ID: bea9d70a3229
Revises: cf2fe0310ab6
Create Date: 2024-05-26 17:06:54.091858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea9d70a3229'
down_revision: Union[str, None] = 'cf2fe0310ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONTRATOS', sa.Column('contestecao_vistoria_inicial_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'CONTRATOS', 'VISTORIAS', ['contestecao_vistoria_inicial_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CONTRATOS', type_='foreignkey')
    op.drop_column('CONTRATOS', 'contestecao_vistoria_inicial_id')
    # ### end Alembic commands ###
