"""empty message

Revision ID: c3b7987395d4
Revises: 
Create Date: 2024-05-26 16:49:56.312620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3b7987395d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CONTRATOS_ibfk_1', 'CONTRATOS', type_='foreignkey')
    op.drop_column('CONTRATOS', 'contestecao_vistoria_inicial_id')
    op.alter_column('SOLICITACOES', 'status',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Enum('ABERTO', 'FECHADO', name='status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SOLICITACOES', 'status',
               existing_type=sa.Enum('ABERTO', 'FECHADO', name='status'),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.add_column('CONTRATOS', sa.Column('contestecao_vistoria_inicial_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('CONTRATOS_ibfk_1', 'CONTRATOS', 'VISTORIAS', ['contestecao_vistoria_inicial_id'], ['id'])
    # ### end Alembic commands ###
