"""empty message

Revision ID: cd1312410a56
Revises: 
Create Date: 2024-05-26 12:08:48.221526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1312410a56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IMOVEIS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USUARIOS_IDENTITY_INFOS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VISTORIAS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ADMINISTRADORES',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ASSISTENTES',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DOCUMENTOS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('documento', sa.LargeBinary(), nullable=True),
    sa.Column('vistoria_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['vistoria_id'], ['VISTORIAS.id'], ),
    sa.PrimaryKeyConstraint('id', 'vistoria_id')
    )
    op.create_table('LOCATARIOS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PRESTADORES_SERVICOS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('especialidade', sa.String(length=255), nullable=True),
    sa.Column('experiencia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CONTRATOS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('esta_ativo', sa.Boolean(), nullable=True),
    sa.Column('criador_id', sa.String(length=36), nullable=True),
    sa.Column('imovel_id', sa.String(length=36), nullable=True),
    sa.Column('locatario_id', sa.String(length=36), nullable=True),
    sa.Column('vistoria_inicial_id', sa.String(length=36), nullable=True),
    sa.Column('contestecao_vistoria_inicial_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['contestecao_vistoria_inicial_id'], ['VISTORIAS.id'], ),
    sa.ForeignKeyConstraint(['criador_id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.ForeignKeyConstraint(['imovel_id'], ['IMOVEIS.id'], ),
    sa.ForeignKeyConstraint(['locatario_id'], ['LOCATARIOS.id'], ),
    sa.ForeignKeyConstraint(['vistoria_inicial_id'], ['VISTORIAS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OCORRENCIAS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=25), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='status'), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('id_contrato', sa.String(length=36), nullable=True),
    sa.Column('criador_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.ForeignKeyConstraint(['id_contrato'], ['CONTRATOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SOLICITACOES',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=25), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='status'), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('contrato_id', sa.String(length=36), nullable=True),
    sa.Column('criador_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['CONTRATOS.id'], ),
    sa.ForeignKeyConstraint(['criador_id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IMAGENS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_imovel', sa.String(length=36), nullable=True),
    sa.Column('id_ocorrencia', sa.String(length=36), nullable=True),
    sa.Column('id_solicitacao', sa.String(length=36), nullable=True),
    sa.Column('id_vistoria', sa.String(length=36), nullable=True),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['id_imovel'], ['IMOVEIS.id'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['OCORRENCIAS.id'], ),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['SOLICITACOES.id'], ),
    sa.ForeignKeyConstraint(['id_vistoria'], ['VISTORIAS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USUARIOS_OCORRENCIAS',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('ocorrencia_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['OCORRENCIAS.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['USUARIOS_IDENTITY_INFOS.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'ocorrencia_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USUARIOS_OCORRENCIAS')
    op.drop_table('IMAGENS')
    op.drop_table('SOLICITACOES')
    op.drop_table('OCORRENCIAS')
    op.drop_table('CONTRATOS')
    op.drop_table('PRESTADORES_SERVICOS')
    op.drop_table('LOCATARIOS')
    op.drop_table('DOCUMENTOS')
    op.drop_table('ASSISTENTES')
    op.drop_table('ADMINISTRADORES')
    op.drop_table('VISTORIAS')
    op.drop_table('USUARIOS_IDENTITY_INFOS')
    op.drop_table('IMOVEIS')
    # ### end Alembic commands ###
