"""empty message

Revision ID: e5cec5893e0d
Revises: 825e30a47efd
Create Date: 2024-05-25 21:37:41.248624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5cec5893e0d'
down_revision: Union[str, None] = '825e30a47efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IMAGENS', sa.Column('id_imovel', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_ocorrencia', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_solicitacao', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_vistoria', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'IMAGENS', 'VISTORIAS', ['id_vistoria'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'IMOVEIS', ['id_imovel'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'SOLICITACOES', ['id_solicitacao'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'OCORRENCIAS', ['id_ocorrencia'], ['id'])
    op.drop_column('IMAGENS', 'id_entidade')
    op.add_column('VISTORIAS', sa.Column('descricao', sa.String(length=500), nullable=True))
    op.drop_constraint('VISTORIAS_ibfk_1', 'VISTORIAS', type_='foreignkey')
    op.drop_column('VISTORIAS', 'esta_fechada_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VISTORIAS', sa.Column('esta_fechada_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('VISTORIAS_ibfk_1', 'VISTORIAS', 'IMAGENS', ['id'], ['id'])
    op.drop_column('VISTORIAS', 'descricao')
    op.add_column('IMAGENS', sa.Column('id_entidade', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_column('IMAGENS', 'id_vistoria')
    op.drop_column('IMAGENS', 'id_solicitacao')
    op.drop_column('IMAGENS', 'id_ocorrencia')
    op.drop_column('IMAGENS', 'id_imovel')
    # ### end Alembic commands ###
