"""empty message

Revision ID: fd59efc9e3a6
Revises: 607922bdb751
Create Date: 2024-05-26 00:21:59.682479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd59efc9e3a6'
down_revision: Union[str, None] = '607922bdb751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IMAGENS', sa.Column('id_imovel', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_ocorrencia', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_solicitacao', sa.String(length=36), nullable=True))
    op.add_column('IMAGENS', sa.Column('id_vistoria', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'IMAGENS', 'IMOVEIS', ['id_imovel'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'SOLICITACOES', ['id_solicitacao'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'OCORRENCIAS', ['id_ocorrencia'], ['id'])
    op.create_foreign_key(None, 'IMAGENS', 'VISTORIAS', ['id_vistoria'], ['id'])
    op.drop_constraint('IMOVEIS_ibfk_1', 'IMOVEIS', type_='foreignkey')
    op.add_column('VISTORIAS', sa.Column('data_criacao', sa.String(length=36), nullable=True))
    op.add_column('VISTORIAS', sa.Column('documento', sa.String(length=36), nullable=True))
    op.add_column('VISTORIAS', sa.Column('id_contrato', sa.String(length=36), nullable=True))
    op.alter_column('VISTORIAS', 'descricao',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('VISTORIAS_ibfk_1', 'VISTORIAS', type_='foreignkey')
    op.create_foreign_key(None, 'VISTORIAS', 'CONTRATOS', ['id_contrato'], ['id'])
    op.drop_column('VISTORIAS', 'esta_fechada_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VISTORIAS', sa.Column('esta_fechada_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'VISTORIAS', type_='foreignkey')
    op.create_foreign_key('VISTORIAS_ibfk_1', 'VISTORIAS', 'IMAGENS', ['id'], ['id'])
    op.alter_column('VISTORIAS', 'descricao',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('VISTORIAS', 'id_contrato')
    op.drop_column('VISTORIAS', 'documento')
    op.drop_column('VISTORIAS', 'data_criacao')
    op.create_foreign_key('IMOVEIS_ibfk_1', 'IMOVEIS', 'IMAGENS', ['id'], ['id'])
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_constraint(None, 'IMAGENS', type_='foreignkey')
    op.drop_column('IMAGENS', 'id_vistoria')
    op.drop_column('IMAGENS', 'id_solicitacao')
    op.drop_column('IMAGENS', 'id_ocorrencia')
    op.drop_column('IMAGENS', 'id_imovel')
    # ### end Alembic commands ###
